name = "createmodpack"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b722f351e0e77613059ea008e4810832f1b84eb9ea5ef9d9082d210913fe98e2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
