name = "createmodpack"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a08dc897574c671ddea6845cf5fdd12de8034fa28cf1beb50b4a4bb2dec97403"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
