name = "createmodpack"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f72a5e0263d93a73bbf79a8b5c5a9efc9f8853c7887d321a18ae476a3a721a24"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
