Platform.mods.kubejs.name = 'Bamsy Mod'

StartupEvents.registry('block', event => {
  event.create('blaze_rod_block')
    .displayName('Block of Blaze Rod')
    .soundType('nether_ore')
    .hardness(3)
    .resistance(2)
    .requiresTool(true)
    .tagBlock('forge:ores')
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_wood_tool')
    .tagBlock('forge:storage_blocks')
  event.create('book_block')
    .displayName('Block of Books')
    .texture(Direction.DOWN, 'kubejs:block/block_book_down')
    .texture(Direction.UP, 'kubejs:block/block_book_up')
    .texture(Direction.SOUTH, 'kubejs:block/block_book_side')
    .texture(Direction.NORTH, 'kubejs:block/block_book_side')
    .texture(Direction.WEST, 'kubejs:block/block_book_side')
    .texture(Direction.EAST, 'kubejs:block/block_book_side')
    .texture('particle', 'minecraft:book')
    .soundType('wood')
    .hardness(2)
    .resistance(1)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/axe')
    .tagBlock('minecraft:needs_wood_tool')
    .tagBlock('forge:storage_blocks')
})
